### ISSUE TITLE
How to setup the project on my local system

### ISSUE THREAD

**Issue by Monson2002** [tangorishi/ReactApp#2]
While I try to setup the project using "create-react-app" , I am encountering this problem

PS C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship> npm run start
Debugger attached.

Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
Waiting for the debugger to disconnect...
C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
PS C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship> npm run start
Debugger attached.

Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
Waiting for the debugger to disconnect...
C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
PS C:\Users\MONSON\OneDrive\Documents\React\ReactApp-Octernship> 

Is there any fix for this ?

Below is the folder structure for reference :>
<img width="158" alt="folder structure" src="https://user-images.githubusercontent.com/91113152/226802887-5bbd2353-547b-4507-894c-400829e23368.png">

**Comment by joyreuben** [comment]
Try running npm install react-scripts@latest
